### ISSUE TITLE
Is it Production Ready?

### ISSUE THREAD

**Issue by Omkaragrawal** [gideaoms/clark-orm#5]
Hey, I was searching for a way to include lucid into one of my Next projects, and I stumbuled upon this great project. While the app.ts in src is fairly simple (and hopefully I understood it as well), the thing I am wondering is, whether it is production ready or not?

I have been using lucid since adonis V5 (2y6m) and now a new project V6 (2m), so I have a fair hands-on on lucid. But the issue I see is the way pplication is initialized in here, wouldn't that need all of the IoC container and other dependencies thus probably creating an issue with NextJS itself?

I would be deploying this NextJS code for one of my client-company, with an avg useage of around 3-5k/minute on minimum. Thus thinking this through. 

While I was searching, I found this reply from Mr. harminder himself: https://github.com/adonisjs/lucid/issues/356#issuecomment-403758208

**Comment by gideaoms** [comment]
Hey! Thanks for checking out the project. I’m glad you found it interesting!

To be upfront, this setup isn’t really production-ready yet. I've been using it mainly for personal side projects, so it hasn’t been fully optimized or stress-tested for high-traffic scenarios like yours. I don't think IoC is a problem because of the way AdonisJS 6 changed how it exposes its packages. I did face some issues using ClarkORM with Next.js, though it works well on a project using standard Node.js. If you’re aiming for production, I'd suggest looking into something like Drizzle.

Hope that helps!

**Comment by Omkaragrawal** [comment]
Hey, thanks a lot, I'll be looking into stress testing and performing a bunch of different tests and let you know, meanwhile looking into Drizzle. Thanks for suggestion.
